/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seg.major;

import javafx.stage.Stage;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.Group;
import seg.major.controller.PrimaryController;
import seg.major.model.util.Props;

public class App extends Application {

    // Name of the view that is shown on first loading the application
    public static String login = "login";
    public static String addPatient = "add_patient";
    public static String patients = "patients";
    public static String schema = "schema";
    public static String propertiesLocation = "props.properties";
    public static Props props;

    public static void main(String[] args) {
        System.out.println("App Started!");
        props = new Props(App.class.getClassLoader().getResource(propertiesLocation));
        System.out.println(props.getProperty("db_url"));
        System.out.println(props.getProperty("db_user"));
        System.out.println(props.getProperty("db_password"));
        System.out.println(props.getProperty("db_name"));
        launch(args);
    }

    /**
     * Start the GUI and load panes
     */
    @Override
    public void start(Stage primaryStage) throws Exception {
        PrimaryController primaryController = new PrimaryController();
        Group root = new Group();
        Scene scene = new Scene(root);

        primaryController.addViews(new String[] { login, addPatient, patients, schema });
        primaryController.setPane(App.login);
        root.getChildren().addAll(primaryController);
        primaryStage.setScene(scene);
        primaryStage.minWidthProperty().bind(primaryController.minWidthProperty());
        primaryStage.minHeightProperty().bind(primaryController.minHeightProperty());
        primaryStage.show();

    }
}
